"""empty message

Revision ID: 218d8e7df9ce
Revises: ce8e2c8e375b
Create Date: 2025-03-16 13:44:32.818862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218d8e7df9ce'
down_revision = 'ce8e2c8e375b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
